In [1]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1)

C:\Users\Ramosan\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [10]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [11]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [12]:
dframe1

X         Y         Z
0  2.482505  1.254704  0.746552
1 -1.231516  0.848170  0.669629
2  1.144937  0.480893 -1.038922
3  1.000964  2.531676  0.662703

In [13]:
dframe2

Y         Q         X
0 -0.061468  0.720196  1.648289
1  1.910143 -1.105413 -0.466199
2  1.645967 -0.345443 -0.082827

In [14]:
pd.concat([dframe1,dframe2])

C:\Users\Ramosan\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN  2.482505  1.254704  0.746552
1       NaN -1.231516  0.848170  0.669629
2       NaN  1.144937  0.480893 -1.038922
3       NaN  1.000964  2.531676  0.662703
0  0.720196  1.648289 -0.061468       NaN
1 -1.105413 -0.466199  1.910143       NaN
2 -0.345443 -0.082827  1.645967       NaN

In [15]:
pd.concat([dframe1,dframe2],ignore_index=True)

C:\Users\Ramosan\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN  2.482505  1.254704  0.746552
1       NaN -1.231516  0.848170  0.669629
2       NaN  1.144937  0.480893 -1.038922
3       NaN  1.000964  2.531676  0.662703
4  0.720196  1.648289 -0.061468       NaN
5 -1.105413 -0.466199  1.910143       NaN
6 -0.345443 -0.082827  1.645967       NaN